### ISSUE TITLE
Revise the type inference part

### ISSUE THREAD

**Issue by izgzhen** [izgzhen/z3-encoding#3]
Esp. the higher order structures like `Map`, `Set`. Interestingly, currently we don't need to infer function type because there is a `SMTContext::_funcContext` which should include everything you need.

**Comment by izgzhen** [comment]
I am trying to embed the small language directly inside Haskell. See `embed` branch for details.

**Comment by izgzhen** [comment]
Looks like the easiest solution to embed qualifier would be make variable not embedded at all...I should make a demo lang for this.

**Comment by izgzhen** [comment]
@zjhmale Ok, I am finally comfortable with its current status now（强迫症终于缓和一点了，赶紧滚去复习期末考）, although it has several problems:

First, `Assertion` is not type-safe, for example `forall v1 v2. (Z3Encoded v1, Z3Encoded v2) => v1 -> v2 -> Assertion`, it doesn't require `v1` and `v2` to be the same `Eq v => v`. We can make stronger requirements here, but that would render the naive term language (rather than a _real_ eDSL in Haskell) in `Z3.Demo` invalid.

Second, pretty lame is that the qualifier still needs a `String` binder and a concrete `Type`. By using Template Haskell, we might be able to resolve this (though it can be difficult IMO).

**Comment by swr1bm86** [comment]
it seems difficult to make HeteroList deriving Eq so as to derive Eq for Term 😂 , i will try later.

> it doesn't require v1 and v2 to be the same Eq v => v.

agreed. binder here is a little bit redundent.

> Second, pretty lame is that the qualifier still needs a String binder and a concrete Type. By using Template Haskell, we might be able to resolve this (though it can be difficult IMO).

**Comment by izgzhen** [comment]
You are right, `HeteroList` is a bad idea. Originally we have manually typed term, so it is possible to bake the `Eq` logic into our `Infer` part

**Comment by izgzhen** [comment]
Looks like TH would be the only way out, unless we manually manage the the Inference etc. It works good, just not that extensible and elegant

**Comment by swr1bm86** [comment]
writing `Macro` is eggache 😂 

> Looks like TH would be the only way out, unless we manually manage the the Inference etc. It works good, just not that extensible and elegant

**Comment by izgzhen** [comment]
I agree

**Comment by swr1bm86** [comment]
sorry, i work on #6 before i see this comment, and do you mean hard code the Eq logic? maybe i'm misunderstanding with this comment.

> You are right, HeteroList is a bad idea. Originally we have manually typed term, so it is possible to bake the Eq logic into our Infer part

**Comment by swr1bm86** [comment]
actually i can not figure out the infer part for now, maybe i should play with z3-haskell first, i used to play with z3 use smtlib2 format scripts.

**Comment by izgzhen** [comment]
@zjhmale I originally mean to write something like `forall v. (Eq v, Z3Encoded v) => v -> v -> Assertion`, but it will require us to inject everything that can appear at that place to be embedded into Haskell type system.

#6 is cool anyway, better than no constraint at all :P

**Comment by izgzhen** [comment]
@zjhmale no hurry. The `z3-haskell`'s interface is not type-safe anyway, so we are not worse at least. I think it is an interesting topic to work on though.

**Comment by swr1bm86** [comment]
ok. so... (那我先去复习啦 😂 )

**Comment by izgzhen** [comment]
I am planning to re-introduce type checking to `Z3Pred`

**Comment by izgzhen** [comment]
Now it is checked by Haskell compiler
