### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by izgzhen** [izgzhen/z3-encoding#4]
I have contacted the author of `z3-haskell` and discussed about updates. It should be resolved in few days or so.

**Comment by swr1bm86** [comment]
that will be great :smile:

**Comment by izgzhen** [comment]
Yes, that should also fix the poor CI that I just tried to put together. (too lazy to fix it manually in yml...)

**Comment by izgzhen** [comment]
Oh no I am wrong. It won't fix entirely either. We also have z3 dep :(

**Comment by izgzhen** [comment]
It is my fault that I mistook the cutting-edge (dev) version z3 as 4.4.1. In the dev version, the compatibility will be broken, but not in 4.4.1 yet. I should revert dep back to stable z3 later again.

See https://github.com/Z3Prover/z3/issues/660 for more info.
