### ISSUE TITLE
Comply to SMT-LIB2 style?

### ISSUE THREAD

**Issue by swr1bm86** [izgzhen/z3-encoding#9]
originally we write smt file like

``` smt
(assert (exists ((x Int) (y Int))
                (not (and (>= (ite (<= x y) x y) x)
                          (>= (ite (<= x y) x y) y)))))
```

and for now we just swap the position with `assert` and logic connectives like

``` haskell
(PExists "x" TyInt $ PExists "y" TyInt $ PNeg $ PConj (PAssert $ GreatE (TmIf (TmLE (TmVar "x") (TmVar "y")) (TmVar "x") (TmVar "y")) $ TmVar "x")
                                                      (PAssert $ GreatE (TmIf (TmLE (TmVar "x") (TmVar "y")) (TmVar "x") (TmVar "y")) $ TmVar "y"), Right Sat)
```

@izgzhen don't you think the second style is not so intuisive, or maybe i'm just in a daze.

**Comment by izgzhen** [comment]
I agree, `PAssert` is a hack I admit. The only reason is to make user-defined assertion `a` parametric as parameter of `PAssert`. btw the lisp-like syntax (esp. `>=`)  looks awkward to me as well.

**Comment by izgzhen** [comment]
Looks like solved, since any assertion is typed as `repr Bool` in host language now.
